create table if not exists public.contact_submissions (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  category text not null,
  subject text not null,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.contact_submissions enable row level security;

grant insert on table public.contact_submissions to anon;

drop policy if exists "Anyone can submit the contact form"
  on public.contact_submissions;

create policy "Anyone can submit the contact form"
  on public.contact_submissions
  for insert
  to anon
  with check (
    char_length(trim(name)) between 1 and 120
    and char_length(trim(email)) between 3 and 320
    and char_length(trim(category)) between 1 and 80
    and char_length(trim(subject)) between 1 and 200
    and char_length(trim(message)) between 1 and 5000
  );
