create table if not exists public.waitlist (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  user_type text not null,
  favorite_sport text,
  referral_code text,
  created_at timestamptz not null default now()
);

create unique index if not exists waitlist_email_unique
  on public.waitlist (lower(email));

alter table public.waitlist enable row level security;

grant insert on table public.waitlist to anon;

drop policy if exists "Anyone can join the waitlist" on public.waitlist;

create policy "Anyone can join the waitlist"
  on public.waitlist
  for insert
  to anon
  with check (true);
